name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Print Java version
        run: java -version

      - name: Download SonarScanner
        run: |
          curl --create-dirs -sSLo /github/home/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip -o /github/home/sonar-scanner.zip -d /github/home/
          echo "/github/home/sonar-scanner-4.6.2.2472-linux/bin" >> $GITHUB_PATH

      - name: Run SonarScanner
        env:
          SONAR_TOKEN: 50b6a990e7d3690b138f59b18c1849205b77e105
        run: |
          sonar-scanner \
            -Dsonar.projectKey=sbahala_CalculateProject \
            -Dsonar.organization=sbahala \
            -Dsonar.sources=src \
            -Dsonar.tests=test \
            -Dsonar.projectBaseDir=. \
            -Dsonar.verbose=true
