
name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Print Java version
        run: java -version

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: 50b6a990e7d3690b138f59b18c1849205b77e105
        with:
          args: >
            -Dsonar.projectKey=sbahala_CalculateProject
            -Dsonar.organization=sbahala
            -Dsonar.sources=src
            -Dsonar.tests=test
            -Dsonar.projectBaseDir=.
            -Dsonar.verbose=true
