# This workflow triggers a SonarCloud analysis of your code and populates
# GitHub Code Scanning alerts with the vulnerabilities found.
# It is provided by a third-party and governed by separate terms of service,
# privacy policy, and support documentation.
# Free for open source projects.

# Steps:
# 1. Login to SonarCloud.io with your GitHub account
# 2. Import your project on SonarCloud, add your GitHub organization, then your repository as a new project.
# 3. Follow the SonarCloud in-product tutorial to obtain your project and organization keys.

name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read  # Allows SonarCloud to decorate PRs with analysis results.

jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Set Java version to 17
          distribution: 'temurin'  # Use Eclipse Temurin distribution for JDK

      - name: Print Java version
        run: java -version

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for PR information
          SONAR_TOKEN: 50b6a990e7d3690b138f59b18c1849205b77e105    # Sonar token from GitHub secrets
        with:
          args: >
            -Dsonar.projectKey=sbahala_CalculateProject
            -Dsonar.organization=sbahala
            # Optional parameters
            #-Dsonar.sources=
            #-Dsonar.tests=
            #-Dsonar.projectBaseDir=.
            #-Dsonar.verbose=true

# Documentation and community support:
# https://docs.sonarcloud.io/getting-started/github/
# https://community.sonarsource.com/c/help/sc/9
